# Generated by Django 4.2.7 on 2023-12-19 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal_profiles', '0002_remove_animal_age_animal_chip_number_and_more'),
        ('appointments', '0002_alter_appointment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='animal_profiles.animal'),
        ),
    ]
