# Generated by Django 4.2.7 on 2023-12-13 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='user',
        ),
    ]
