# Generated by Django 4.2.7 on 2023-12-17 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_remove_medication_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medication',
            old_name='next_dosage_time',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='medication',
            name='dosage_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='medication',
            name='dosage_interval',
            field=models.DurationField(default=datetime.timedelta(seconds=21600)),
        ),
    ]
