# Generated by Django 4.2.7 on 2023-12-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0003_rename_next_dosage_time_medication_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
