# Generated by Django 4.2.7 on 2023-12-20 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0004_alter_medication_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='dosage_interval',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='start_time',
        ),
        migrations.AddField(
            model_name='medication',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 20, 11, 11, 18, 609458, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medication',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 20, 11, 11, 30, 216977, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medication',
            name='dosage_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='medication',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
