# Generated by Django 4.2.7 on 2023-12-20 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal_profiles', '0002_remove_animal_age_animal_chip_number_and_more'),
        ('medications', '0005_remove_medication_dosage_interval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='animal_profiles.animal'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
