# Generated by Django 4.2.7 on 2024-01-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_profiles', '0002_remove_animal_age_animal_chip_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='pedigree_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
